### ISSUE TITLE
HTTP_ONLY vs input cookies

### ISSUE THREAD

**Issue by jonthegeek** [r4ds/cookies#54]
If a cookie is HTTP_ONLY, it's in the request object, but it will never be in input. Therefore we should sort something out for dealing with those in the case where you have both types. I think we need the user to explicitly tell get_cookies() that they want to look for an http_only cookie (ie, never check input).

**Comment by jonthegeek** [comment]
Another option: Keep track of names of cookies that are successfully deleted during the session. Maybe even delete them from the session$request object, if that's possible. Then we don't need to track them. Hmm.

**Comment by mbjohnsonmn** [comment]
Running the sample app in the documentation, both on localhost and shinyapps.io, I can't get past this error/warning: 

Warning: Error in cookies::set_cookie: ✖ Cannot update cookie selected_number.
ℹ HttpOnly cookies can only be updated via set_cookie_response().
  1: runApp

Any advice appreciated.

**Comment by jonthegeek** [comment]
> Running the sample app in the documentation, both on localhost and shinyapps.io, I can't get past this error/warning:
> 
> Warning: Error in cookies::set_cookie: ✖ Cannot update cookie selected_number. ℹ HttpOnly cookies can only be updated via set_cookie_response(). 1: runApp
> 
> Any advice appreciated.

Is it possible you already had a cookie from a previous version? If so, clear that cookie via the browser before running things.

If that doesn't work, please open a new issue with details, and I'll look into it the next time I'm digging into this package (hopefully soon). Thanks!

**Comment by mbjohnsonmn** [comment]
Thanks for the quick response. I cleared my browser's cookies but no joy, so I will work on creating an issue. Basically, I was hoping to use the simple app example to help troubleshoot a different problem I am having with a much larger app, namely very poor performance on shinyapps.io, even though it works well on the localhost. ~cheers.
