### ISSUE TITLE
"Shiny.setInputValue is not a function" on load

### ISSUE THREAD

**Issue by avsdev-cw** [r4ds/cookies#66]
It looks like the library is registering before Shiny loads (we have some quite large applications).

Traceback says the culprit is this listener:
```js
window.addEventListener('focus', function() {
  getCookies();
});
```

I've tried both devel and released (0.2.2) versions

**Comment by jonthegeek** [comment]
Thanks for the report! I'll look into it as soon as I can. We have some other racetime issues with Shiny, so I suspect a general hardening in that area will make a lot of things simpler.

**Comment by jonthegeek** [comment]
I *think* this will fix your issues. Please let me know if it doesn't! I'm submitting this to CRAN in any case to fix a breaking issue in the tests, but hopefully it's a real fix!
