### ISSUE TITLE
shinyapp.ts:437 TypeError: Cannot read properties of null (reading 'readyState')

### ISSUE THREAD

**Issue by mbjohnsonmn** [r4ds/cookies#67]
Hi Jon. I've spent a long time trying to isolate this error. It appeared last Friday (9/1) without any changes to my code. I've narrowed it down to section that loops through a set of 'get_cookie' calls - nine to be exact. In the R console, I get, "Warning: Error in if: argument of length zero." Not much help. Here is the text of the full error in the browser:

shinyapp.ts:437 TypeError: Cannot read properties of null (reading 'readyState')
    at e.value (shinyapp.ts:584:25)
    at e.value (shinyapp.ts:459:12)
    at e.value (inputBatchSender.ts:65:23)
    at inputBatchSender.ts:47:19
    at e.<anonymous> (shinyapp.ts:430:22)
    at v (shinyapp.ts:5:1357)
    at Generator.<anonymous> (shinyapp.ts:5:4174)
    at Generator.next (shinyapp.ts:5:2208)
    at F_ (shinyapp.ts:6:99)
    at u (shinyapp.ts:7:194)

Again, not much help for me, but a comment/solution to a [similar post in SO that mentions typos in JS code](https://stackoverflow.com/questions/18338041/cannot-read-property-readystate-of-undefined) I recall you mentioning that you may be doing some work there? 

I also noticed that the sample app in the documentation no longer works. It throws this error: 
Warning: Error in set_cookie: ✖ Cannot update cookie selected_number.
ℹ HttpOnly cookies can only be updated via set_cookie_response().

As always, thanks for your great work on the package. 

Morris

**Comment by jonthegeek** [comment]
@mbjohnsonmn Have you installed the dev version of the package? Try it out if not. It isn't a final fix, but it fixes the sample app issue.

```
# install.packages("remotes")
remotes::install_github("r4ds/cookies")
```

I think something changed in Shiny timing that broke {cookies}. I'm hoping to find time to dig deep into this package again in a few weeks, HOPEFULLY I can implement a more stable fix then.

Let me know whether the dev version helps!

**Comment by jonthegeek** [comment]
I *think* this will fix your issues. Please let me know if it doesn't! I'm submitting this to CRAN in any case to fix a breaking issue in the tests, but hopefully it's a real fix!
