### ISSUE TITLE
Set HttpOnly cookie

### ISSUE THREAD

**Issue by ESCRI11** [r4ds/cookies#68]
Hello Jon.

I have noticed on the reference of the package that using `set_cookie_response` should be able to set an HttpOnly cookie. However I can't seem to get it working. Could you please provide some guidance or an extremely simple toy app?

Thank you!

**Comment by avais88786** [comment]
Can we get an example of the above please? Apologies if I missed any obvious links but the ticket closed without updates :)

**Comment by jonthegeek** [comment]
@avais88786 the asker closed the ticket. I opened a new, related ticket at #74 with a couple notes to myself about what to do. If you have a specific thing you don't understand about it or a specific use-case in mind, please let me know over there!

**Comment by avais88786** [comment]
> @avais88786 the asker closed the ticket. I opened a new, related ticket at #74 with a couple notes to myself about what to do. If you have a specific thing you don't understand about it or a specific use-case in mind, please let me know over there!

Appreciate it, thanks
